name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - uses: cypress-io/github-action@v6
        with:
          command: npm run cypress
        env:
          CYPRESS_baseUrl: https://front.serverest.dev/login
          CYPRESS_user_email: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_user_password: ${{ secrets.CYPRESS_USER_PASSWORD }}